project 'GrandmasCookbook.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '13.2'

target 'GrandmasCookbook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GrandmasCookbook

	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'

end
